/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.bilal7596;

import io.github.bilal7596.list.LinkedList;

import static io.github.bilal7596.utilities.StringUtils.join;
import static io.github.bilal7596.utilities.StringUtils.split;
import static io.github.bilal7596.MessageUtils.getMessage;

import io.github.bilal7596.sb.LombokSetterGetter;
import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));

        LombokSetterGetter lombokSetterGetter = new LombokSetterGetter();
        System.out.println(lombokSetterGetter.getName());
    }
}
