/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.bilal7596;

class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }
}
